apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grumpycat
resources:
- ../../base


images:
- name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs
  newTag: v0.7.0
- name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat
  newTag: v0.7.0
- name: quay.io/wpernath/cat-multiplayer:latest
  newName: quay.io/wpernath/cat-multiplayer
  newTag: v0.7.0


# generate a configmap 
configMapGenerator:
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server and multiplayer server service
  # 
  # NOTE: This will automatically be read from client config map
  - name: client-config
    literals:
      - APPLICATION_BASESERVERURL=http://cat-server-grumpycat.apps.cat2.ocp.lan/
      - APPLICATION_BASEMULTIPLAYERSERVERURL=http://cat-multiplayer-grumpycat.apps.cat2.ocp.lan/

  # GrumpyCat Server configmap, just point to the internal service name of the kafka service
  - name: server-config
    literals:
      - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092      

  # GrumpyCat Multiplayer Server config map
  - name: multiplayer-config
    literals:
      - INFINISPAN_SERVER=paul
      - INFINISPAN_USER=kuhn
      - INFINISPAN_PASS=karl
